/* 第 6 章 潮港市命案：子查詢、綜合推理、INSERT INTO solution */
SD.chapters.push({
  id: 6,
  slug: 'ch6',
  title: '海景大樓命案',
  subtitle: '子查詢與綜合推理',
  cover: './images/ch6.webp',
  skills: ['子查詢', 'IN (SELECT ...)', 'MAX 子查詢', 'HAVING', '綜合推理'],
  badge: { id: 'detective', name: '名偵探', img: './images/badge-detective.webp', desc: '獨力破解潮港市命案，找出兇手與幕後主使。' },
  steps: [
    { type: 'story', lines: [
      { who: 'narrator', text: '8 月 15 日，雨夜。海濱區海景大道「海景大樓」。住戶游致遠被發現死在自家客廳。' },
      { who: 'chief', text: '這案子我們查了一個月，卡在一開始：報案紀錄只寫了「兩名目擊者」，沒寫名字。你有資料庫，去把他們找出來。' },
      { who: 'mentor', text: '這章不再逐題告訴你該從哪張表下手；線索在證詞裡，方法你大多學過，需要新招時我會補一課。卡住時提示還在。從 crime_report 開始。' },
    ] },
    { type: 'task', id: 'c6-t1', title: '案件檔案', prompt: '從 <code>crime_report</code> 找出 <code>crime_type</code> 為<strong>命案</strong>的案件，顯示 <code>id</code>、<code>report_date</code>、<code>description</code>。',
      hints: ["WHERE crime_type = '命案'", 'SELECT 三個欄位，FROM crime_report。', "<code>SELECT id, report_date, description FROM crime_report WHERE crime_type = '命案';</code>"],
      check: { kind: 'result', cols: ['id', 'report_date', 'description'], ordered: false },
      clue: { title: '兩名目擊者', text: '第一位住在海濱路門牌號碼最大的那一戶；第二位姓林，住在中央路。' } },
    { type: 'lesson', title: '子查詢：把一個查詢的結果當條件', body: `
      <p>「海濱路門牌最大的那戶」需要先算出最大門牌，再拿它去找人。可以分兩步，也可以用<strong>子查詢</strong>一次完成：</p>
      <pre><code>SELECT name FROM person
WHERE street = '海濱路'
  AND house_no = (SELECT MAX(house_no) FROM person WHERE street = '海濱路');</code></pre>
      <p>括號裡的 SELECT 先執行，結果（一個數字）代入外層條件。子查詢回傳多個值時，改用 <code>IN (SELECT ...)</code>。</p>` },
    { type: 'blocks', id: 'c6-b1', title: '拼出子查詢', prompt: '組出「住海濱路、門牌最大的市民 <code>name</code>」。子查詢整段是一塊積木。',
      blocks: ['SELECT', 'name', 'FROM', 'person', 'WHERE', "street = '海濱路'", 'AND', 'house_no =', "(SELECT MAX(house_no) FROM person WHERE street = '海濱路');"],
      wrong: '外層還是 SELECT … FROM … WHERE …，子查詢放在條件的等號右邊。' },
    { type: 'task', id: 'c6-t2', title: '目擊者一', prompt: '找出住在<strong>海濱路</strong>、<strong>門牌號碼最大</strong>的市民，顯示 <code>id</code>、<code>name</code>、<code>house_no</code>。',
      hints: ['用子查詢算 MAX(house_no)，或 ORDER BY house_no DESC LIMIT 1。', "WHERE street = '海濱路' AND house_no = (SELECT MAX(house_no) FROM person WHERE street = '海濱路')", "<code>SELECT id, name, house_no FROM person WHERE street = '海濱路' AND house_no = (SELECT MAX(house_no) FROM person WHERE street = '海濱路');</code>"],
      check: { kind: 'result', cols: ['id', 'name', 'house_no'], ordered: false },
      clue: { title: '目擊者一', text: '郭淑芬（編號 20），海濱路 388 號。' } },
    { type: 'task', id: 'c6-t3', variant: 'debug', title: '目擊者二', prompt: '一個月前同事查過<strong>姓林</strong>、住在<strong>中央路</strong>的市民，這句 SQL 回傳 0 筆，案子就卡在這裡。找出問題並修正，顯示 <code>id</code>、<code>name</code>。',
      starter: "SELECT id, name FROM person WHERE name LIKE '林' AND street = '中央路';",
      hints: ["姓林 → name LIKE '林%'", "AND street = '中央路'", "<code>SELECT id, name FROM person WHERE name LIKE '林%' AND street = '中央路';</code>"],
      check: { kind: 'result', cols: ['id', 'name'], ordered: false },
      clue: { title: '目擊者二', text: '林佩君（編號 21），中央路。' } },
    { type: 'task', id: 'c6-t4', title: '兩人的證詞', prompt: '用<strong>一句 SQL</strong>取出兩位目擊者的筆錄：<code>interview</code> 中 <code>person_id</code> 屬於上面兩人的紀錄，顯示 <code>person_id</code>、<code>transcript</code>。可以直接寫 IN (20, 21)，也可以挑戰用子查詢。',
      hints: ['WHERE person_id IN (20, 21)', "子查詢版：WHERE person_id IN (SELECT id FROM person WHERE (name LIKE '林%' AND street = '中央路') OR (street = '海濱路' AND house_no = (SELECT MAX(house_no) FROM person WHERE street = '海濱路')))", '<code>SELECT person_id, transcript FROM interview WHERE person_id IN (20, 21);</code>'],
      check: { kind: 'result', cols: ['person_id', 'transcript'], ordered: false },
      clue: { title: '證詞重點', text: '① 男性，背「潮港健身」金卡會員包，會員卡號 48Z 開頭，黑色汽車，車牌字母含 H、數字 42 開頭。② 8 月 9 日曾在健身房見過他。' } },
    { type: 'task', id: 'c6-t5', title: '48Z 金卡會員', prompt: '從 <code>gym_member</code> 找出 <code>id</code> 以 <strong>48Z</strong> 開頭且 <code>membership_status</code> 為<strong>金卡</strong>的會員，顯示 <code>id</code>、<code>name</code>、<code>person_id</code>。',
      hints: ["id LIKE '48Z%'", "AND membership_status = '金卡'", "<code>SELECT id, name, person_id FROM gym_member WHERE id LIKE '48Z%' AND membership_status = '金卡';</code>"],
      check: { kind: 'result', cols: ['id', 'name', 'person_id'], ordered: false },
      clue: { title: '兩名金卡會員', text: '48Z7A 蔡明哲（22）、48Z55 張偉倫（23）。' } },
    { type: 'predict', id: 'c6-p1', title: 'IN 接子查詢', sql: "SELECT name FROM person WHERE id IN (SELECT person_id FROM gym_member WHERE id LIKE '48Z%');", question: '48Z 開頭的會員有兩位。這句會回傳？', options: ['1 筆，子查詢只取第一個', '2 筆', '會出錯，子查詢不能回傳多列'], answer: 1, explain: 'IN 可以接回傳多列的子查詢，每一個值都會被比對。若把 IN 改成 =，MariaDB 就會因為子查詢回傳多列而報錯。' },
    { type: 'task', id: 'c6-t6', title: '8 月 9 日誰在健身房？', prompt: '把 <code>gym_member</code> 與 <code>gym_checkin</code> 接起來（<code>membership_id = id</code>），找出 <strong>48Z 開頭</strong>的會員在 <strong>2025-08-09</strong> 的打卡，顯示 <code>m.name</code>、<code>c.checkin_time</code>。',
      hints: ['JOIN gym_checkin c ON c.membership_id = m.id', "WHERE m.id LIKE '48Z%' AND c.checkin_date = '2025-08-09'", "<code>SELECT m.name, c.checkin_time FROM gym_member m JOIN gym_checkin c ON c.membership_id = m.id WHERE m.id LIKE '48Z%' AND c.checkin_date = '2025-08-09';</code>"],
      check: { kind: 'result', cols: ['name', 'checkin_time'], ordered: false },
      clue: { title: '兩人都在', text: '蔡明哲與張偉倫 8 月 9 日下午都有打卡。要靠車牌分辨。' } },
    { type: 'task', id: 'c6-t7', title: '車牌決勝', prompt: '把 <code>person</code> 與 <code>driver_license</code> 接起來（<code>p.license_id = d.id</code>），在編號 <strong>22、23</strong> 之中找出車牌<strong>字母含 H</strong> 且<strong>數字以 42 開頭</strong>的人，顯示 <code>p.name</code>、<code>d.plate_number</code>、<code>d.car_color</code>。',
      hints: ["車牌格式是 ABC-1234：LIKE '%H%-42%'", 'WHERE p.id IN (22, 23) AND d.plate_number LIKE ...', "<code>SELECT p.name, d.plate_number, d.car_color FROM person p JOIN driver_license d ON d.id = p.license_id WHERE p.id IN (22, 23) AND d.plate_number LIKE '%H%-42%';</code>"],
      check: { kind: 'result', cols: ['name', 'plate_number', 'car_color'], ordered: false },
      clue: { title: '兇手鎖定', text: '蔡明哲，黑色汽車 KHT-4271。' } },
    { type: 'lesson', title: '提交答案：INSERT INTO solution', body: `
      <p>局裡的結案系統是一張叫 <code>solution</code> 的表。把你認定的兇手姓名<strong>新增</strong>進去，系統會告訴你對不對：</p>
      <pre><code>INSERT INTO solution (answer) VALUES ('姓名');
SELECT * FROM solution;</code></pre>` },
    { type: 'solution', id: 'c6-s1', title: '提交兇手', prompt: '用 <code>INSERT INTO solution (answer) VALUES (\'姓名\');</code> 提交你認定的<strong>兇手</strong>。',
      hints: ['車牌那題查到的姓名就是要提交的答案。', "<code>INSERT INTO solution (answer) VALUES ('___');</code>", "<code>INSERT INTO solution (answer) VALUES ('蔡明哲');</code>"],
      success: '沒錯，兇手是蔡明哲。但他被逮捕後起初只說了一句話：「我是收錢辦事的。」這案子還沒完。',
      fail: '不是這個人。回頭看車牌那一題：字母含 H、數字 42 開頭的是哪一輛？',
      clue: { title: '兇手落網', text: '蔡明哲承認行兇，但聲稱受人雇用，拒絕說出雇主姓名。' } },
    { type: 'story', lines: [
      { who: 'suspect', text: '我不會告訴你們她的名字。她很有錢，身高大概 165 到 168，一頭紅髮，開 Tesla Model S。她 7 月去聽了三次「潮港交響音樂會」，事情就是在那裡談的。' },
      { who: 'mentor', text: '他以為這樣說等於沒說。他不知道我們有駕照資料、活動打卡、收入資料，還有一個會寫 SQL 的人。' },
    ] },
    { type: 'task', id: 'c6-t8', title: '兇手的完整筆錄', prompt: '用<strong>子查詢</strong>取出蔡明哲的筆錄：<code>interview</code> 中 <code>person_id</code> 等於 <code>(SELECT id FROM person WHERE name = \'蔡明哲\')</code> 的 <code>transcript</code>。',
      hints: ["WHERE person_id = (SELECT id FROM person WHERE name = '蔡明哲')", '子查詢只回傳一個值時可以用 =。', "<code>SELECT transcript FROM interview WHERE person_id = (SELECT id FROM person WHERE name = '蔡明哲');</code>"],
      check: { kind: 'value' } },
    { type: 'task', id: 'c6-t9', title: '紅髮、Tesla Model S、165~168', prompt: '接起 <code>person</code> 與 <code>driver_license</code>，找出 <code>hair_color</code> 為<strong>紅</strong>、<code>car_brand</code> 為 <strong>Tesla</strong>、<code>car_model</code> 為 <strong>Model S</strong>、身高 <strong>165 到 168</strong> 的人，顯示 <code>p.id</code>、<code>p.name</code>、<code>d.car_color</code>。',
      hints: ['四個條件都在 driver_license 表。', "d.hair_color = '紅' AND d.car_brand = 'Tesla' AND d.car_model = 'Model S' AND d.height_cm BETWEEN 165 AND 168", "<code>SELECT p.id, p.name, d.car_color FROM person p JOIN driver_license d ON d.id = p.license_id WHERE d.hair_color = '紅' AND d.car_brand = 'Tesla' AND d.car_model = 'Model S' AND d.height_cm BETWEEN 165 AND 168;</code>"],
      check: { kind: 'result', cols: ['id', 'name', 'car_color'], ordered: false },
      clue: { title: '三名符合的女性', text: '沈若蘭（24）、朱曼玲（25）、鍾芷若（26）都是紅髮、開 Tesla Model S。' } },
    { type: 'task', id: 'c6-t10', title: '7 月去了三次音樂會的人', prompt: '從 <code>event_checkin</code> 找出 <code>event_name</code> 為<strong>潮港交響音樂會</strong>、<code>event_date</code> 在 <strong>2025 年 7 月</strong>、且<strong>恰好 3 次</strong>的 <code>person_id</code>，顯示 <code>person_id</code> 與次數（別名 <code>cnt</code>）。',
      hints: ["event_date LIKE '2025-07%'", 'GROUP BY person_id HAVING COUNT(*) = 3', "<code>SELECT person_id, COUNT(*) AS cnt FROM event_checkin WHERE event_name = '潮港交響音樂會' AND event_date LIKE '2025-07%' GROUP BY person_id HAVING COUNT(*) = 3;</code>"],
      check: { kind: 'result', cols: null, ordered: false },
      clue: { title: '唯一符合', text: '只有市民編號 24 在 7 月去了三次音樂會。' } },
    { type: 'task', id: 'c6-t11', title: '她是誰、多有錢？', prompt: '把 <code>person</code> 與 <code>income</code>（<code>person_id</code>）接起來，顯示編號 24 的 <code>p.name</code>、<code>p.street</code>、<code>i.annual_income</code>。',
      hints: ['JOIN income i ON i.person_id = p.id', 'WHERE p.id = 24', '<code>SELECT p.name, p.street, i.annual_income FROM person p JOIN income i ON i.person_id = p.id WHERE p.id = 24;</code>'],
      check: { kind: 'result', cols: ['name', 'street', 'annual_income'], ordered: false },
      clue: { title: '幕後主使', text: '沈若蘭，海景大道 1 號，年收入 1,280 萬。她與死者游致遠是同一條街的鄰居。' } },
    { type: 'task', id: 'c6-t12', title: '挑戰：一句話找出她', prompt: '用<strong>一句 SQL</strong>直接得到幕後主使的姓名：外層從 <code>person</code> + <code>driver_license</code> 篩出 <code>hair_color = \'紅\'</code>、Tesla Model S、身高 165~168 的人，再加上 <code>p.id IN (子查詢：7 月去三次音樂會的 person_id)</code>。只顯示 <code>p.name</code>。',
      hints: ['把上兩題合併：外層 JOIN 條件 + AND p.id IN ( ... )', '子查詢就是 c6-t10 那句，但只 SELECT person_id。', "<code>SELECT p.name FROM person p JOIN driver_license d ON d.id = p.license_id WHERE d.hair_color = '紅' AND d.car_brand = 'Tesla' AND d.car_model = 'Model S' AND d.height_cm BETWEEN 165 AND 168 AND p.id IN (SELECT person_id FROM event_checkin WHERE event_name = '潮港交響音樂會' AND event_date LIKE '2025-07%' GROUP BY person_id HAVING COUNT(*) = 3);</code>"],
      check: { kind: 'value' } },
    { type: 'solution', id: 'c6-s2', title: '提交幕後主使', prompt: '再一次 <code>INSERT INTO solution (answer) VALUES (\'姓名\');</code> 提交<strong>幕後主使</strong>。',
      hints: ['三名紅髮 Tesla 車主中，只有一位 7 月去了三次音樂會。', "<code>INSERT INTO solution (answer) VALUES ('___');</code>", "<code>INSERT INTO solution (answer) VALUES ('沈若蘭');</code>"],
      success: '破案！沈若蘭因土地糾紛買兇殺害鄰居游致遠。你從兩句模糊的證詞出發，用 SQL 一路追到雇主。潮港市警局從今天起有了真正的資料偵探。',
      fail: '不是她。用 HAVING COUNT(*) = 3 那題的 person_id 對回 person 表。',
      clue: { title: '全案偵破', text: '兇手蔡明哲、主使沈若蘭皆已到案。動機：海景大道土地開發糾紛。' } },
    { type: 'quiz', id: 'c6-q1', question: 'WHERE id = (SELECT ...) 與 WHERE id IN (SELECT ...) 的差別是？', options: ['沒有差別', '= 用於子查詢只回傳一個值，IN 用於可能多個值', 'IN 比較快', '= 只能用在數字'], answer: 1, explain: '子查詢回傳多列時用 = 會出錯，要改用 IN。' },
    { type: 'story', lines: [
      { who: 'chief', text: '一個月沒進展的案子，你用資料庫一個下午就結了。從今天起，資料分析組正式納入編制，你是第一位正式組員。' },
      { who: 'mentor', text: '記住你走過的路：SELECT 看資料、WHERE 篩選、函數處理時間與文字、GROUP BY 找異常、JOIN 串證據、子查詢把一切接起來。這些在任何一個 MariaDB 資料庫裡都一樣好用。' },
      { who: 'narrator', text: '潮港市的夜色依舊，霓虹倒映在港灣。而你知道，每一盞燈後面，都有一筆等著被查出來的資料。' },
    ] },
  ],
});
